//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocHospital
    {
        public int id { get; set; }
        public string Hospitalname { get; set; }
        public string Hospitaladdress { get; set; }
        public string State { get; set; }
        public string Otherinfo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string mobile { get; set; }
    }
}
