//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocRegistraton
    {
        public int id { get; set; }
        public string docname { get; set; }
        public string docusername { get; set; }
        public string docpassword { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public string Specialty { get; set; }
        public string hospital { get; set; }
        public string OtherInfo { get; set; }
        public string uploadfile { get; set; }
        public Nullable<int> hostype { get; set; }
        public Nullable<int> cattype { get; set; }
        public Nullable<int> approve { get; set; }
        public string address { get; set; }
        public string state { get; set; }
    }
}
