//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemedyTable
    {
        public int id { get; set; }
        public string Remedy { get; set; }
        public string Definition { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> cattype { get; set; }
        public string Causes { get; set; }
        public string Prevention { get; set; }
    }
}
