//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMedHistory
    {
        public int id { get; set; }
        public Nullable<int> docid { get; set; }
        public Nullable<int> userid { get; set; }
        public string ailment { get; set; }
        public string treatment_prescribe { get; set; }
        public string test_done { get; set; }
        public string recommendation { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string testresult { get; set; }
        public Nullable<int> appointid { get; set; }
    }
}
